version: '3.9'

services:
  keycloak-sso:
    image: quay.io/keycloak/keycloak:26.1.0
    container_name: keycloak-sso
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_local
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: Keycloak2025
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: 'false'
      KC_PROXY: edge
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_LOG_LEVEL: DEBUG
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - keycloak_data:/opt/keycloak/data

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak_local
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Keycloak2025
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  keycloak_data:
  postgres_data:
